apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: petclinic-image-updater
  namespace: argocd
spec:
  commonUpdateSettings:
    pullSecret: argocd/ecr-secret
  applicationRefs:
    - namePattern: petclinic-app
      useAnnotations: true
