apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devsecops-petclinic-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - petclinic-dev
  selector:
    matchLabels:
      app: devsecops-petclinic
  endpoints:
    - port: http
      path: /
      interval: 15s