apiVersion: v1
kind: Service
metadata:
  name: devsecops-petclinic-service
  namespace: petclinic-dev
  labels:
    app: devsecops-petclinic
spec:
  type: ClusterIP
  selector:
    app: devsecops-petclinic
  ports:
    - name: http
      port: 8080
      targetPort: 8080